function [scenario, egoVehicle] = LKAS()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.10 (R2021a) and Automated Driving Toolbox 3.3 (R2021a).
% Generated on: 30-Apr-2021 16:17:02

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-67.7 -3.10862e-15 0;
    -7.5 -4.7 0;
    29 -3.10862e-15 0;
    42.8 0.5 0;
    59 -3.10862e-15 0;
    105.9 -18.9 0;
    152.4 -12.4 0;
    172.498 27.2484 0;
    201.3 55.8 0;
    241.8 49 0;
    266.3 15.7 0;
    285.2 -28.3 0;
    322.8 -49.8 0;
    351 -38.8 0;
    378.5 -16.1 0;
    434.7 -56.1 0;
    467.7 -66.3 0;
    496.7 -40.5 0;
    538.9 -43.5 0];
laneSpecification = lanespec(3);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-63.7217260796085 -0.221042395071266 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-66.1217260796085 -0.121042395071285 0;
    -19.8 -5.9 0;
    14.4 -0.8 0;
    42.8 1.5 0;
    64.9000000000001 -1.50000000000001 0;
    95.6 -14.2 0;
    133.2 -22.5 0;
    160.9 -3.5 0;
    184.4 44 0;
    217.1 59.6 0;
    261.1 27.2 0;
    278.8 -14.8 0;
    327.1 -49.6 0;
    361.7 -30.5 0;
    389.8 -15.3 0;
    428.3 -49 0;
    467.2 -67.2 0;
    504.4 -37.8 0;
    539.9 -42.8 0];
speed = 13.9;
trajectory(egoVehicle, waypoints, speed);

